apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin4
  name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: ghcr.io/jmcarbo/pgadmin:v5.0.0
        #imagePullPolicy: Always
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: foo@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: foobar
        - name: TZ
          value: CET
      restartPolicy: Always
